server:
  port: 8300
spring:
  application:
    name: cart-services
  redis:
    host: 192.168.99.100
    port: 6379

logging:
  level:
    root: INFO
    com.helpserviceprovider.cartservice: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

